[backdrop]
blur_intensity = 0.0
tint_intensity = 0.0

[bar.default]
attach_panels = false
background_opacity = 0.80000001192092896
center = []
end = []
margin_edge = 5
padding = 20
start = []

    [bar.default.monitor.DP-1]
    background_opacity = 0.99999997764825821
    center = [ "audio_visualizer_1", "clock", "audio_visualizer_2" ]
    end = [ "media", "volume", "input_volume", "tray" ]
    margin_edge = 0
    margin_ends = 0
    padding = 26
    radius_bottom_left = -80
    radius_bottom_right = -80
    radius_top_right = -17
    start = [ "control-center", "workspaces", "cat" ]
    thickness = 30

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "on_surface_variant"
        id = "g1"
        members = [ "cpu", "clock", "ram" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.DP-1.capsule_group]]
        border = ""
        fill = "surface_variant"
        id = "g2"
        members = [ "Control_Center", "workspaces_2", "cat_3" ]
        opacity = 1.0
        padding = 12.0

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "surface_variant"
        id = "g3"
        members = [ "audio_visualizer", "clock", "audio_visualizer" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "surface_variant"
        id = "g6"
        members = [ "media", "volume", "input_volume" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "surface"
        id = "g5"
        members = [ "audio_visualizer", "clock", "audio_visualizer" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "surface_variant"
        id = "g8"
        members = [ "active_window", "clock" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.DP-1.capsule_group]]
        fill = "surface_variant"
        id = "g7"
        members = [ "control-center", "workspaces", "cat" ]
        opacity = 1.0
        padding = 6.0

    [bar.default.monitor.HDMI-A-2]
    enabled = false

    [[bar.default.capsule_group]]
    fill = "on_surface_variant"
    id = "g1"
    members = [ "cpu", "clock", "ram" ]
    opacity = 1.0
    padding = 6.0

[control_center]
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "power_profile"

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900

[keybinds]
down = [ "Ctrl+j" ]
left = [ "Ctrl+h" ]
right = [ "Ctrl+l" ]
up = [ "Ctrl+k" ]

[location]
address = "Singapore"
auto_locate = false

[lockscreen]
blur_intensity = 0.0
monitors = [ "DP-1" ]
wallpaper = "/home/stalkingwolf/Pictures/Wallpapers/130205952_p0.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000001"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "DP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "HDMI-A-2"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 231.12007141113281
    box_width = 1386.720458984375
    cx = 1280.0
    cy = 1324.43994140625
    output = "DP-1"
    rotation = 0.0
    scale = 3.108069896697998
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        aspect_ratio = 6.0
        background = false
        bands = 40.0
        centered = false
        mirrored = true
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 122.0
    box_width = 275.0
    cx = 1289.5
    cy = 253.0
    output = "DP-1"
    rotation = 0.0
    scale = 1.3571428060531616
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false

[noctalia_state]
setup_wizard_completed = true

[notification]
layer = "overlay"
monitors = [ "DP-1" ]
scale = 0.69999999999999996

[osd]
keyboard_layout = false
lock_keys = false
monitors = [ "DP-1" ]
position = "bottom_center"

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/translator" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

[shell]
app_icon_color = "tertiary"
avatar_path = "/home/stalkingwolf/nervi-mornye-far.jpg"
font_family = "Maple Mono"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
offline_mode = true
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
telemetry_enabled = true
ui_scale = 1.2

    [shell.panel]
    control_center_placement = "centered"
    launcher_categories = false
    session_placement = "centered"
    transparency_mode = "soft"
    wallpaper_placement = "centered"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "m"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "Ctrl+s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "s"
    variant = "destructive"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Lavender"
custom_palette = "CatppuccinBlue"
source = "custom"
wallpaper_scheme = "Ayu"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/stalkingwolf/Pictures/Wallpapers"
fill_color = "#1E1E2E"
per_monitor_directories = true

    [wallpaper.automation]
    enabled = true
    interval_minutes = 10

    [wallpaper.default]
    path = "/home/stalkingwolf/Pictures/Wallpapers/b5048cb088b946e608e65724a873cc352011343.jpg"

    [wallpaper.last]
    path = "/home/stalkingwolf/Pictures/Wallpapers/136182205_p0.jpg"

    [wallpaper.monitor.DP-1]
    directory = "/home/stalkingwolf/Pictures/Wallpapers"

    [wallpaper.monitor.HDMI-A-2]
    directory = "/home/stalkingwolf/Pictures/Wallpapers"

    [wallpaper.monitors.DP-1]
    path = "/home/stalkingwolf/Pictures/Wallpapers/wallhaven_9ozew1.jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/stalkingwolf/Pictures/Wallpapers/136182205_p0.jpg"

[weather]
address = "Singapore, Singapore"
enabled = false
refresh_minutes = 5

[widget.Control_Center]
capsule = true
custom_image = "/run/current-system/sw/share/icons/hicolor/scalable/apps/nix-snowflake-white.svg"
scale = 1.2
type = "control-center"

[widget.audio_visualizer]
width = 125.0

[widget.audio_visualizer_1]
color_2 = "secondary"
type = "audio_visualizer"

[widget.audio_visualizer_2]
color_1 = "secondary"
type = "audio_visualizer"

[widget.bongocat]
audio_spectrum = true
input_device = ""
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"
use_mpris_filter = true

[widget.cat]
input_device = "/dev/input/event1"
input_devices = [ "/dev/input/event2" ]
scale = 1.1000000000000001
type = "noctalia/bongocat:cat"

[widget.cat_2]
type = "noctalia/bongocat:cat"

[widget.cat_3]
capsule = true
input_devices = [ "/dev/input/event2" ]
type = "noctalia/bongocat:cat"

[widget.clock]
anchor = false
capsule = false
color = "primary"

[widget.control-center]
custom_image = "/run/current-system/sw/share/icons/hicolor/scalable/apps/nix-snowflake-white.svg"
scale = 1.1000000000000001

[widget.control_center]
custom_image = "/run/current-system/sw/share/icons/hicolor/scalable/apps/nix-snowflake-white.svg"
type = "control-center"

[widget.cpu]
show_label = false

[widget.input_volume]
color = "on_surface"
show_label = false

[widget.media]
anchor = false
art_size = 32.0
hide_when_no_media = true
max_length = 150

[widget.ram]
show_label = false

[widget.tray]
drawer = true
match_adjacent_spacing = true

[widget.volume]
color = "on_surface"
show_label = false

[widget.workspaces]
capsule_radius = 8
display = "none"
hide_when_empty = true
labels_only_when_occupied = true

[widget.workspaces_2]
capsule = true
display = "none"
hide_when_empty = true
labels_only_when_occupied = true
type = "workspaces"
